name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resource Group
      run: |
        az group create --name myResourceGroup --location eastus

    - name: Create Azure Service Principal
      id: sp
      run: |
        SP_CREDENTIALS=$(az ad sp create-for-rbac --name myServicePrincipal --role contributor --scopes /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup --sdk-auth)
        echo "SP_CREDENTIALS=$SP_CREDENTIALS" >> $GITHUB_ENV

    - name: Create AKS Cluster
      run: |
        az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys --service-principal ${{ env.SP_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          pg_deployment.yaml
          pg_service.yaml
        images: hftamayo/pgecommerce:0.0.1
        namespace: default
        secret-name: pg-credentials
        containers: pgecommerce
        imagepullsecrets: myImagePullSecret
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}