name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resource Group
      run: |
        az group create --name myResourceGroup --location eastus

    - name: Create Azure Service Principal
      id: sp
      run: |
        SP_CREDENTIALS=$(az ad sp create-for-rbac --name myServicePrincipal --role contributor --scopes /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup --sdk-auth)
        echo "SP_CREDENTIALS=$SP_CREDENTIALS" >> $GITHUB_ENV

    - name: Create AKS Cluster
      run: |
        az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys --service-principal ${{ env.SP_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

    - name: Create Docker Hub Secret
      run: |
        kubectl create secret docker-registry regcred \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username=${{ secrets.DOCKER_HUB_USERNAME }} \
          --docker-password=${{ secrets.DOCKER_HUB_PAT }} \
          --docker-email=your-email@example.com

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_HUB_PAT }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Pull Docker image
      run: |
        docker pull hftamayo/pgecommerce:0.0.1

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          pg_deployment.yaml
          pg_service.yaml
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}